spring.application.name=CodeSync
server.servlet.context-path=/codesync
server.port=8082

#MSSSQL MY LOCAL
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=db
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JPA/Hibernate settings
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
# logging.level.org.springframework=DEBUG



# Comma-separated blocked IPs
security.blocked-ips=103.121.40.46

# Rate limit config
security.rate.limit.capacity=100
security.rate.limit.refill.seconds=1
security.rate.limit.to.refill=1



# ============================================
# Security Configuration
# ============================================

# Default admin credentials (change these in production!)
dashboard.admin.username=${CODESYNC_DASHBOARD_ADMIN_NAME}
dashboard.admin.password=${CODESYNC_DASHBOARD_ADMIN_PASS}

# Optional: Additional user credentials
dashboard.user.username=${CODESYNC_DASHBOARD_USER_NAME}
dashboard.user.password=${CODESYNC_DASHBOARD_USER_PASS}




# ============================================
# Session Configuration
# ============================================

# Session cookie configuration
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
# Set to true in production with HTTPS:
# server.servlet.session.cookie.secure=true

# Session timeout (in seconds) 1800
server.servlet.session.timeout=1800


# ============================================
# ACTUATOR
# ============================================
# Expose the endpoints you want (health,info,metrics,env or '*' for all)
management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*
# Show full health details (otherwise it just says "UP") "always","never","when-authorized"
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN




