spring.application.name=CodeSync
server.servlet.context-path=/codesync
server.port=8082


codesync.version=V-2.1.0
codesync.version.date=2026-07-14

# ============================================
# Database Config
# ============================================

#MSSSQL MY LOCAL
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=db
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=none
### use this below if first time so tables get created
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
# logging.level.org.springframework=DEBUG



# ============================================
# File Sharing Config
# ============================================

# File Sharing
codesync.upload-dir=/mnt/8EFED7B1FED79037/UBUNTU-BACKUP/VS-GIT/CodeSync (java25-branch)/TEST
codesync.archive-dir=/mnt/8EFED7B1FED79037/UBUNTU-BACKUP/VS-GIT/CodeSync (java25-branch)/TEST2/ARCHIVER

spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

#Max File Size and Quantity
codesync.max-file-size=120MB
codesync.max-total-files=10


# File expiry duration
codesync.file-expiry.days=0
codesync.file-expiry.hours=12
codesync.file-expiry.minutes=0

# How often to run the expiry check 
codesync.file-expiry.cron.enabled=true
codesync.file-expiry.cron=0 0 0/3 * * *

# how often to run file moving schedular
codesync.file-moving.cron.enabled=false
codesync.file-moving.cron=0 0 11,15,18 * * *


# WORKS ON THIS
# Direct Deletion 
# codesync.file.deletion.enabled=false

# WinSCP config
codesync.winscp.enabled=false

codesync.winscp.sftp-host=${CODESYNC_WINSCP_IP}
codesync.winscp.sftp-user=${CODESYNC_WINSCP_USER}
codesync.winscp.sftp-password=${CODESYNC_WINSCP_PASS}

codesync.winscp.exe-path=C:\\Program Files (x86)\\WinSCP\\WinSCP.com
codesync.winscp.script.directory=C:\\Users\\Administrator\\Desktop\\Umair-HFs\\logs\\codesync\\temp
codesync.winscp.remote-base-path=/mnt/8EFED7B1FED79037/UBUNTU-BACKUP/shared/223/scp-test


# ============================================
# Security Configuration
# ============================================

# Rate limit config
security.rate.limit.capacity=100
security.rate.limit.refill.seconds=1
security.rate.limit.to.refill=1


# Default admin credentials (change these in production!)
dashboard.admin.username=${CODESYNC_DASHBOARD_ADMIN_NAME}
dashboard.admin.password=${CODESYNC_DASHBOARD_ADMIN_PASS}

# Optional: Additional user credentials
dashboard.user.username=${CODESYNC_DASHBOARD_USER_NAME}
dashboard.user.password=${CODESYNC_DASHBOARD_USER_PASS}


# Comma-separated list of allowed IPs for /logsService
# Use 'LOCAL_ONLY' to restrict to localhost only
logsservice.allowed-ips=127.0.0.1,::1,172.191.1.223,172.190.1.223



# ============================================
# Session Configuration
# ============================================

# Session cookie configuration
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
# Set to true in production with HTTPS:
# server.servlet.session.cookie.secure=true

# Session timeout (in seconds) 1800
server.servlet.session.timeout=1800


# ============================================
# ACTUATOR
# ============================================
# Expose the endpoints you want (health,info,metrics,env or '*' for all)
management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*
# Show full health details (otherwise it just says "UP") "always","never","when-authorized"
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN

management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true



# ============================================
# SWAGGER CONFIG ---> Only Use In DEV Environment
# ============================================

# NOTE: Please Keep it false in UAT/PROD
# -------------------------------- >>>>> 
swagger.enabled=true
# -------------------------------- >>>>> 

springdoc.api-docs.enabled=${swagger.enabled:false}
springdoc.swagger-ui.enabled=${swagger.enabled:false}

# Collapse all swagger tags by default
springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.swagger-ui.defaultModelExpandDepth=1
springdoc.swagger-ui.docExpansion=none

# To See Request Duration
springdoc.swagger-ui.displayRequestDuration=true

# To Enable Try It Out By Default
springdoc.swagger-ui.tryItOutEnabled=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html






